import argparse
import sys
import pandas as pd
import numpy as np
import plotly.express as px
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(
        description="Step 2: Generate Interactive Plotly Benchmark Plot (V2)"
    )
    parser.add_argument(
        "--input_csv",
        default="step2_out/step2_mixture_model_benchmark_results.csv",
        help="Path to the tabular benchmark results CSV generated by the Mixture Model script."
    )
    args = parser.parse_args()

    csv_path = Path(args.input_csv)

    if not csv_path.exists():
        print(f"[ERROR] Tabular results CSV not found at: {csv_path}")
        print("Please verify your path or make sure you ran the Mixture Model pipeline first.")
        sys.exit(1)

    print(f"Loading results from: {csv_path}...")
    df = pd.read_csv(csv_path)

    # 2. Formatear datos para Plotly Express (Melt)
    methods = {
        'Unique_Pct': 'Unique Peptides Only',
        'LCA_Pct': 'Rigid LCA Assignment',
        'Mix_Pct': 'Mixture Model'
    }
    melted = []
    for col, name in methods.items():
        temp = df[['Node', 'Node_Type', 'Num_Species', 'Condition', 'Expected_Pct', col]].copy()
        temp.rename(columns={col: 'Measured_Pct'}, inplace=True)
        temp['Method'] = name
        melted.append(temp)
    plot_df = pd.concat(melted, ignore_index=True)

    # Filtrar ceros para escala logarítmica
    plot_df = plot_df[(plot_df['Expected_Pct'] > 0.0) & (plot_df['Measured_Pct'] > 0.0)]

    # 3. Crear el gráfico de dispersión interactivo
    fig = px.scatter(
        plot_df,
        x='Expected_Pct',
        y='Measured_Pct',
        color='Num_Species',
        symbol='Node_Type',
        facet_row='Condition',
        facet_col='Method',
        hover_name='Node',
        hover_data={
            'Node_Type': True,
            'Num_Species': True,
            'Expected_Pct': ':.4f',
            'Measured_Pct': ':.4f',
            'Condition': False,
            'Method': False
        },
        category_orders={
            "Condition": ["Constant", "Protein", "Uneven"],
            "Method": ["Unique Peptides Only", "Rigid LCA Assignment", "Mixture Model"]
        },
        color_continuous_scale='Viridis',
        labels={
            'Expected_Pct': 'Expected Abundance (%)',
            'Measured_Pct': 'Measured Abundance (%)',
            'Num_Species': 'Descendants',
            'Node_Type': 'Type'
        }
    )

    # 4. Ajustar diseño, escalas logarítmicas y tamaños
    fig.update_xaxes(type="log", matches='x')
    fig.update_yaxes(type="log", matches='y')

    # Establecer límites fijos para todos los subplots
    fig.update_xaxes(range=[np.log10(0.003), np.log10(110)])
    fig.update_yaxes(range=[np.log10(0.003), np.log10(110)])

    # Agregar la línea diagonal 1:1 de referencia a cada faceta
    for row in range(1, 4):
        for col in range(1, 4):
            fig.add_shape(
                type="line",
                x0=0.005, y0=0.005,
                x1=100, y1=100,
                line=dict(color="Red", width=1.5, dash="dash"),
                row=row, col=col
            )

    fig.update_layout(
        title={
            'text': "<b>Metaproteomics Benchmark: Unique vs Rigid LCA vs Mixture Model</b><br><sup>Usa el mouse para hacer zoom, arrastra para paneo, doble clic para resetear y pasa el cursor por los puntos</sup>",
            'y': 0.98,
            'x': 0.5,
            'xanchor': 'center',
            'yanchor': 'top'
        },
        height=950,
        width=1050,
        coloraxis_colorbar=dict(
            title="Descendants",
            ticks="outside"
        ),
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        ),
        margin=dict(t=100, b=50, l=50, r=50)
    )

    # Mostrar en Colab
    fig.show()

if __name__ == "__main__":
    main()
