import argparse
import sys
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(
        description="Step 2: Generate Accuracy Boxplots and Correlation Summaries (V2)"
    )
    parser.add_argument(
        "--input_csv",
        default="step2_out/step2_mixture_model_benchmark_results.csv",
        help="Path to the tabular benchmark results CSV generated by the Mixture Model script."
    )
    parser.add_argument(
        "--outdir",
        default="./step2_out",
        help="Directory to save the generated accuracy plots."
    )
    args = parser.parse_args()

    csv_path = Path(args.input_csv)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    if not csv_path.exists():
        print(f"[ERROR] Benchmark results CSV not found at: {csv_path}")
        print("Please verify the path or make sure you ran the Mixture Model pipeline first.")
        sys.exit(1)

    print(f"Loading results from: {csv_path}...")
    df = pd.read_csv(csv_path)

    # 1. GENERATE ERROR BOXPLOT (LFC ERROR)
    print("Generating Error Boxplot...")
    # Filter positive values to avoid log10 of 0 or negative numbers
    df_pos = df[(df["Expected_Pct"] > 0) & (df["Unique_Pct"] > 0) & (df["LCA_Pct"] > 0) & (df["Mix_Pct"] > 0)].copy()
    
    if df_pos.empty:
        print("[WARNING] No valid positive abundance values found for boxplot calculation.")
    else:
        df_pos["Unique (Discard Shared)"] = np.abs(np.log10(df_pos["Unique_Pct"]) - np.log10(df_pos["Expected_Pct"]))
        df_pos["Rigid LCA (Paso 2)"] = np.abs(np.log10(df_pos["LCA_Pct"]) - np.log10(df_pos["Expected_Pct"]))
        df_pos["Mixture Model (Proposed)"] = np.abs(np.log10(df_pos["Mix_Pct"]) - np.log10(df_pos["Expected_Pct"]))

        # Melt for seaborn boxplot
        melt_cols = ["Unique (Discard Shared)", "Rigid LCA (Paso 2)", "Mixture Model (Proposed)"]
        df_melted = df_pos.melt(
            id_vars=["Condition", "Node_Type"],
            value_vars=melt_cols,
            var_name="Method",
            value_name="Log10_Error"
        )

        plt.figure(figsize=(14, 7))
        sns.set_theme(style="whitegrid")
        
        # Custom palette matching our 3x3 colormaps (Blues, Oranges, Greens)
        colors = ["#3182bd", "#e6550d", "#2ca25f"]
        
        ax = sns.boxplot(
            data=df_melted,
            x="Condition",
            y="Log10_Error",
            hue="Method",
            palette=colors,
            width=0.6,
            linewidth=1.5,
            fliersize=5
        )
        
        plt.title("Taxonomic Quantification Accuracy: Distribution of Abundance Error\n"
                  "Error calculated as absolute difference in Log10 space (lower is better)", 
                  fontsize=14, fontweight="bold", pad=15)
        plt.xlabel("Experimental Mixture Condition", fontsize=12, fontweight="bold")
        plt.ylabel("Absolute Log10 Abundance Error\n|log10(Measured) - log10(Expected)|", fontsize=12, fontweight="bold")
        plt.legend(title="Quantification Method", title_fontsize='11', loc="upper right", frameon=True)
        plt.tight_layout()

        boxplot_path = outdir / "step2_mixture_model_error_boxplot.png"
        plt.savefig(boxplot_path, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"[SUCCESS] Error boxplot saved to: {boxplot_path}")


    # 2. GENERATE GROUPED BAR CHART OF CORRELATIONS
    print("Generating Correlation Summary Plot...")
    conditions = ["Constant", "Protein", "Uneven"]
    methods_cols = ["Unique_Pct", "LCA_Pct", "Mix_Pct"]
    methods_names = ["Unique Only", "Rigid LCA", "Mixture Model"]
    colors = ["#3182bd", "#e6550d", "#2ca25f"]

    corr_data = []
    for cond in conditions:
        sub = df[(df["Condition"] == cond) & (df["Expected_Pct"] > 0.0)].copy()
        for col_name, label in zip(methods_cols, methods_names):
            valid = sub[sub[col_name] > 0.0]
            if len(valid) > 2:
                # Calculate Log Pearson r
                log_r = np.log10(valid["Expected_Pct"]).corr(np.log10(valid[col_name]), method="pearson")
                # Calculate Log Spearman R
                log_s = np.log10(valid["Expected_Pct"]).corr(np.log10(valid[col_name]), method="spearman")
            else:
                log_r, log_s = np.nan, np.nan
                
            corr_data.append({
                "Condition": cond,
                "Method": label,
                "Log_Pearson_r": log_r,
                "Log_Spearman_R": log_s
            })

    corr_df = pd.DataFrame(corr_data)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7), sharey=True)

    # Plot Pearson
    sns.barplot(
        data=corr_df,
        x="Condition",
        y="Log_Pearson_r",
        hue="Method",
        palette=colors,
        ax=ax1,
        edgecolor="black",
        linewidth=1
    )
    ax1.set_title("Log-Scale Pearson Correlation (r)\n(Measures linear alignment along diagonal)", fontsize=12, fontweight="bold")
    ax1.set_xlabel("Condition", fontsize=11, fontweight="bold")
    ax1.set_ylabel("Correlation Coefficient", fontsize=11, fontweight="bold")
    ax1.set_ylim(-0.2, 1.05)
    ax1.grid(True, linestyle="--", alpha=0.5)
    ax1.legend().remove()

    # Annotate bars
    for p in ax1.patches:
        height = p.get_height()
        if not np.isnan(height):
            ax1.annotate(f'{height:.3f}',
                        (p.get_x() + p.get_width() / 2., height),
                        ha='center', va='bottom',
                        xytext=(0, 3), textcoords='offset points',
                        fontsize=9, fontweight="bold")

    # Plot Spearman
    sns.barplot(
        data=corr_df,
        x="Condition",
        y="Log_Spearman_R",
        hue="Method",
        palette=colors,
        ax=ax2,
        edgecolor="black",
        linewidth=1
    )
    ax2.set_title("Log-Scale Spearman Correlation (R)\n(Measures rank-order monotonic consistency)", fontsize=12, fontweight="bold")
    ax2.set_xlabel("Condition", fontsize=11, fontweight="bold")
    ax2.set_ylabel("")
    ax2.grid(True, linestyle="--", alpha=0.5)
    ax2.legend(title="Method", title_fontsize='10', loc="lower right", frameon=True)

    # Annotate bars
    for p in ax2.patches:
        height = p.get_height()
        if not np.isnan(height):
            ax2.annotate(f'{height:.3f}',
                        (p.get_x() + p.get_width() / 2., height),
                        ha='center', va='bottom',
                        xytext=(0, 3), textcoords='offset points',
                        fontsize=9, fontweight="bold")

    plt.suptitle("Quantitative Performance Comparison Across All 3 Conditions\n"
                 "Comparing Log-scale Pearson and Spearman correlations (higher is better)", 
                 fontsize=14, fontweight="bold", y=0.98)
    plt.tight_layout()

    corr_plot_path = outdir / "step2_mixture_model_correlation_summary.png"
    plt.savefig(corr_plot_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"[SUCCESS] Correlation summary plot saved to: {corr_plot_path}")

if __name__ == "__main__":
    main()
